[project]
name = "geoproject-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django==5.2",
    "psycopg>=3.2.6",
    "python-dotenv>=1.1.0",
]
